### ISSUE TITLE
Make sure custom-set-variables and custom-set-faces are before Customizations

### ISSUE THREAD

**Issue by luisgerhorst** [flyingmachine/emacs-for-clojure#10]
I very new to emacs but I just had a lot of trouble because `custom-set-variables` and `custom-set-faces` were run after the scripts in `customizations`.

For example, I tried to install [emacs-color-theme-solarized](https://github.com/sellout/emacs-color-theme-solarized) and I put all commands listed under their install section into `themes.el` and simply could no make it work.

I also found [this](http://zeekat.nl/articles/making-emacs-work-for-me.html) emacs config and they made `customise` put all it's directives into a extra file which seems to be a good idea.

Please excuse me if the stuff I'm telling is pure garbage ;) just wanted to share my problems and see if it helps.

**Comment by flyingmachine** [comment]
Thanks for letting me know. It's strange that that would be the cause for you, as the `custom-set-variables` calls seem harmless. Were you also still [loading the tomorrow night theme](https://github.com/flyingmachine/emacs-for-clojure/blob/master/customizations/ui.el#L29)?

**Comment by luisgerhorst** [comment]
No, I added the Solarized directory to my `custom-theme-load-path` and then `(load-theme 'solarized)`. Two things that seem to be the problem are `custom-safe-themes` so you don't get asked every time you open Emacs if Solarized should be allowed to execute code and `frame-background-mode` to choose the light / dark theme. Both have to be set before the Solarized code gets executed.
