### ISSUE TITLE
An error occurred while loading the emacs.d file

### ISSUE THREAD

**Issue by jwatki06** [flyingmachine/emacs-for-clojure#11]
When starting Emacs (on OSX 10.8.5) this error occurs: 
File error: http://melpa.milkbox.net/packages/exec-path-from-shell-20140731.907.el, Not found

**Comment by flyingmachine** [comment]
Sorry about that - if you run “git pull” in .emacs.d and try opening emacs again it should work

**Comment by jwatki06** [comment]
All working now. Thanks for the super quick response.
