### ISSUE TITLE
{:user {:plugins [[cider/cider-nrepl "0.8.1"]]}}

### ISSUE THREAD

**Issue by Txellenne** [flyingmachine/emacs-for-clojure#12]
Hi! Just wondering whether I got it right or not. There on your (very instructive) site it's advised to create a profile `*.clj` file before starting the *flyingmachine* emacs which should reads the following line; `{:user {:plugins [[cider/cider-nrepl "0.8.1"]]}}` but the current version of the cider-mode package file at melpa is 0.8.2. On other side, the version of the cider-mode package you ship hereby reads to be 0.7.0. Should I skip this?, maybe the script itself takes care of installing the currently available one package? (well, I'm probably a little puzzled with so wide band an range of info.. )
I'd appreciate any clue on this.
Txe.

**Comment by flyingmachine** [comment]
Sorry for the confusion! You should be able to go ahead with the instructions as they are. The github repo uses cider 0.8.1 (I haven’t updated it for 0.8.2). Some of the version references are wrong - going to clean them up soonish. If the instructions give you trouble, please let me know :)

**Comment by Txellenne** [comment]
Yeap, all goes great!! Thanks!!

**Comment by flyingmachine** [comment]
Great!
