### ISSUE TITLE
M-x package-install RET geiser RET

### ISSUE THREAD

**Issue by Txellenne** [flyingmachine/emacs-for-clojure#13]
Hi, I was trying to use this emacs setting also to learn scheme with  guile, I know it's probably out of scope here, but as to install [geiser] (http://www.nongnu.org/geiser/geiser_2.html#Installation) as repl it's advised just get it from ELPA I just noted that your `init.el` has the following lines commented so I was wondering if is there any expected issue I should get into consideration when I did it. 
```lisp
14 ;; (setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
15 ;; ("marmalade" . "http://marmalade-repo.org/packages/")
16 ;; ("melpa" . "http://melpa-stable.milkbox.net/packag
```
I'd appreciate your help on this.
Txe

**Comment by Txellenne** [comment]
Ok, I got an idea by reading [this](http://stackoverflow.com/questions/14836958/updating-packages-in-emacs) discussion, I leave the stackoverflow link here just in case it helps someone else,
Thanks.

**Comment by flyingmachine** [comment]
This is a great resource. Thank you!
