### ISSUE TITLE
update README with instructions on how to update CIDER

### ISSUE THREAD

**Issue by flyingmachine** [flyingmachine/emacs-for-clojure#22]

**Comment by gonewest818** [comment]
I'm sure you know this, but with cider 0.11.0 and newer, cider-nrepl is automagically loaded in the repl, and one doesn't need to explicitly mention cider-nrepl in ~/.lein/profiles.clj.  So when I upgraded I actually went back and deleted that line.  thanks-

**Comment by flyingmachine** [comment]
This is useful, thanks!
