### ISSUE TITLE
Cannot run REPL via cider-jack-in after package upgrade

### ISSUE THREAD

**Issue by stanislavgrujic** [flyingmachine/emacs-for-clojure#30]
I downloaded the configuration zip file and did as instructed in the installation manual.
As I started Emacs, I ran the ```M-x package-list-packages``` and upgraded packages to the newer versions.
After the Emacs is restarted, REPL cannot be started anymore.
During Emacs startup there is a message saying *Symbol's function definition is void: global-rainbow-delimiters-mode*.
PR #17 seems to make this message go away, but the REPL still cannot be started. 

The message which is reported, when I try to run ```M-x cider-jack-in``` is *Symbol's function definition is void: nil*.

The same issue occurs if I clone the repo and upgrade packages in Emacs.

**Comment by flyingmachine** [comment]
I think this has been resolved
