### ISSUE TITLE
Setting up emacs-for-clojure without wiping out 'emacs.d/' directory

### ISSUE THREAD

**Issue by ofenerci** [flyingmachine/emacs-for-clojure#32]
Hello, 
I am using Prelude Emacs and would like to set up clojure without wiping out my `.emacs.d/` directory. Which files are necessary to put into that directory that  I could closely get to the the environment of "emacs-for-clojure"

**Comment by flyingmachine** [comment]
Hi! Sorry it has taken me more than 2.5 years to respond. I hope you got your setup working :) But to answer your question: I don't know, and I don't think I have time to figure out the answer :( Sorry!
