### ISSUE TITLE
what about visiting `clojurescritpt` files...

### ISSUE THREAD

**Issue by touxstone** [flyingmachine/emacs-for-clojure#39]
Hi, I'm trying to gain literacy also with `clojurescript` & following this otherwise so wonderful `emacs-for-clojure settings` (and some other tutoriales) but whenever I visit a `*.cljs` file with Emacs I got the following warning: 
```elisp
[WARNING] Something in your configuration activated ‘clojure-mode’ instead of ‘clojurescript-mode’ in this buffer.
This could cause problems.
(See ‘clojure-verify-major-mode’ to disable this message.)
```
I'm not sure so just asking whether this has to do with the following below line and script & If so, does anyone know to tell how-to correct it? (it could seem some obvious but what I wanted to check is whether or not there is something else I had to do, namely install new Emacs packages or making additional corrections. I'd appreciate any help.
https://github.com/flyingmachine/emacs-for-clojure/blob/c169ec14f97b2ed3fad57153d9f35282f7e9d0c9/customizations/setup-clojure.el#L54

**Comment by santiagocabrera96** [comment]
Just change it to use clojurescript-mode like this and you are good to go:

(add-to-list 'auto-mode-alist '("\\.cljs.*$" . clojurescript-mode))
